CREATE DATABASE AgendaContactosDB;
GO

USE AgendaContactosDB;
GO

CREATE TABLE Contactos (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Nombre NVARCHAR(MAX) NOT NULL,
    Telefono NVARCHAR(MAX) NOT NULL,
    Celular NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(MAX) NOT NULL,
    FechaCreacion DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO
